#:kivy 1.0.9

<MissionBar>:
    rows: 2
    columns: 2
    Button:
        text: "Mission 1"
        on_release: root.set_mission("Mission 1")
    Button:
        text: "Mission 2"
        on_release: root.set_mission("Mission 2")
    Button:
        text: "Mission 3"
        on_release: root.set_mission("Mission 3")
    Button:
        text: "Mission 4"
        on_release: root.set_mission("Mission 4")